---
- hosts: app
  gather_facts: yes
  become: yes
  roles:
    - 00_preparing
    - { role: 01_centos_docker-ce, when: ansible_distribution == "CentOS" }
    - { role: 01_ubuntu_docker-ce, when: ansible_distribution == "Ubuntu" }

- hosts: database
  gather_facts: no
  become: yes
  roles:
    - postgresql-server

